import styles from "../styles/Home.module.css";
import Head from "next/head";
import { useState } from "react";
import { Header } from "./components/Header/Header.jsx";
import { Main } from "./components/Main/Main.jsx";
import { Footer } from "./components/Footer/styles/Footer.jsx";

// Inspiration template Url - https://nicepage.com/website-templates/preview/building-and-architecture-109231?device=desktop

const Home = () => {
  const [copyright, setCopyright] = useState(
    "©2024 STUDIO. ALL RIGHTS RESERVED"
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>How we work</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main />

      <Footer text={copyright} />
    </div>
  );
};

export default Home;
